name: Manual-build
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag'
        required: true
        default: 'latest' 
        type: string
env:
  #BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  BUILDKIT_IMAGE: jkaninda/nginx-fpm
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set environment for branch
        run: |
          set -x
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "TAG_NAME=latest" >> "$GITHUB_ENV"
            echo "runs-on: main branch"
          else
            echo "TAG_NAME=${{ github.head_ref || github.ref_name }}" >> "$GITHUB_ENV"
            echo "runs-on: ${{ github.head_ref || github.ref_name }} branch"
          fi
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push based on alpine
        uses: docker/build-push-action@v3
        with:
          push: true
          file: "./src/Dockerfile.alpine"
          platforms: linux/amd64,linux/arm64
          tags: |
           "${{env.BUILDKIT_IMAGE}}:alpine"
      -
        name: Build and push stable version
        uses: docker/build-push-action@v3
        with:
          push: true
          file: "./src/Dockerfile"
          platforms: linux/amd64,linux/arm64
          tags: |
           "${{env.BUILDKIT_IMAGE}}:${{env.TAG_NAME}}"
           "${{env.BUILDKIT_IMAGE}}:stable"
          
